// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class BeginRandomRotation {
        
        public RandomRotation Group;
        
        private RandomRotation _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode15_go = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode15_component = default( UnityEngine.MonoBehaviour );
        
        private UnityEngine.Rigidbody ActionNode15_Result = default( UnityEngine.Rigidbody );
        
        private UnityEngine.Vector3 ActionNode16_Result = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode17_a = default( UnityEngine.Vector3 );
        
        private float ActionNode17_b = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode17_Result = default( UnityEngine.Vector3 );
        
        public RandomRotation Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode15_go = Group.Entity.gameObject;
            // ActionNode
            // Visit uFrame.ECS.Actions.UnityLibrary.GetRigidbody
            ActionNode15_Result = uFrame.ECS.Actions.UnityLibrary.GetRigidbody(ActionNode15_go, ActionNode15_component);
            // ActionNode
            // Visit uFrame.ECS.Actions.CreateRandoms.GetInsideSphere
            ActionNode16_Result = uFrame.ECS.Actions.CreateRandoms.GetInsideSphere();
            ActionNode17_a = ActionNode16_Result;
            ActionNode17_b = Group.Tumble;
            // ActionNode
            // Visit uFrame.ECS.Actions.Vector3Library.Multiply
            ActionNode17_Result = uFrame.ECS.Actions.Vector3Library.Multiply(ActionNode17_a, ActionNode17_b);
            // SetVariableNode
            ActionNode15_Result.angularVelocity = (UnityEngine.Vector3)ActionNode17_Result;
        }
    }
}
