// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.APIs;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class BeginMultipleIntervalSpawn {
        
        public SpawnMultipleAtInterval Group;
        
        private SpawnMultipleAtInterval _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private float ActionNode14_Seconds = default( System.Single );
        
        private uFrame.ECS.APIs.IEcsComponent ActionNode14_DisposeWith = default( uFrame.ECS.APIs.IEcsComponent );
        
        private uFrame.ECS.Actions.IntervalBySeconds ActionNode14 = new uFrame.ECS.Actions.IntervalBySeconds();
        
        private System.IDisposable ActionNode14_Result = default( System.IDisposable );
        
        private UnityEngine.GameObject GetRandomListItem15_Result = default( UnityEngine.GameObject );
        
        private UnityEngine.GameObject ActionNode16_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.Vector3 ActionNode16_position = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode16_rotation = default( UnityEngine.Vector3 );
        
        private UnityEngine.GameObject ActionNode16_Result = default( UnityEngine.GameObject );
        
        public SpawnMultipleAtInterval Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode14_Seconds = Group.SpawnSpeed;
            ActionNode14_DisposeWith = Group;
            // ActionNode
            // Visit uFrame.ECS.Actions.IntervalBySeconds
            ActionNode14.Seconds = ActionNode14_Seconds;
            ActionNode14.DisposeWith = ActionNode14_DisposeWith;
            ActionNode14.System = System;
            ActionNode14.Tick = ActionNode14_Tick;
            ActionNode14.Execute();
            ActionNode14_Result = ActionNode14.Result;
        }
        
        private void ActionNode14_Tick() {
            ActionNode14_Result = ActionNode14.Result;
            // GetRandomListItem
            GetRandomListItem15_Result = Group.Items[UnityEngine.Random.Range(0, Group.Items.Count)];
            ActionNode16_gameObject = GetRandomListItem15_Result;
            // ActionNode
            // Visit uFrame.ECS.Actions.GameObjects.Instantiate
            ActionNode16_Result = uFrame.ECS.Actions.GameObjects.Instantiate(ActionNode16_gameObject, ActionNode16_position, ActionNode16_rotation);
            // SetVariableNode
            ActionNode16_Result.transform.parent = (UnityEngine.Transform)Group.Parent;
        }
    }
}
