// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DisableUI {
        
        public WavesGame Group;
        
        private WavesGame _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private uFrameECSExample.MenuUI LoopGroupNode39_Item = default( uFrameECSExample.MenuUI );
        
        private UnityEngine.GameObject ActionNode40_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode40_behaviour = default( UnityEngine.MonoBehaviour );
        
        public WavesGame Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // LoopGroupNode
            var LoopGroupNode39_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSExample.MenuUI>().Components;
            for (var LoopGroupNode39_ItemIndex = 0
            ; LoopGroupNode39_ItemIndex < LoopGroupNode39_GroupComponents.Count; LoopGroupNode39_ItemIndex++
            ) {
                LoopGroupNode39_Item = LoopGroupNode39_GroupComponents[LoopGroupNode39_ItemIndex];
                LoopGroupNode39_Next();
            }
        }
        
        private void LoopGroupNode39_Next() {
            ActionNode40_gameObject = LoopGroupNode39_Item.gameObject;
            // ActionNode
            // Visit uFrame.ECS.Actions.GameObjects.DeactiateGameObject
            uFrame.ECS.Actions.GameObjects.DeactiateGameObject(ActionNode40_gameObject, ActionNode40_behaviour);
        }
    }
}
