// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GunnerInputUpdateHandler {
        
        public PlayerGunner Group;
        
        private uFrame.ECS.APIs.ISystemUpdate _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private UnityEngine.KeyCode ActionNode36_key = default( UnityEngine.KeyCode );
        
        private UnityEngine.KeyCode EnumValueNode35 = KeyCode.Space;
        
        private bool ActionNode36_Result = default( System.Boolean );
        
        private uFrameECSExample.Gun LoopCollectionNode37_Item = default( uFrameECSExample.Gun );
        
        private uFrameECSExample.GunState EnumValueNode40 = GunState.Shooting;
        
        private uFrameECSExample.Gun LoopCollectionNode38_Item = default( uFrameECSExample.Gun );
        
        private uFrameECSExample.GunState EnumValueNode42 = GunState.Idle;
        
        public uFrame.ECS.APIs.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode36_key = EnumValueNode35;
            // ActionNode
            // Visit uFrame.ECS.Actions.InputLibrary.IsKeyDown
            ActionNode36_Result = uFrame.ECS.Actions.InputLibrary.IsKeyDown(ActionNode36_key, ActionNode36_yes, ActionNode36_no);
        }
        
        private void LoopCollectionNode37_Next() {
            // SetVariableNode
            LoopCollectionNode37_Item.State = (uFrameECSExample.GunState)EnumValueNode40;
        }
        
        private void ActionNode36_yes() {
            // LoopCollectionNode
            for (var LoopCollectionNode37_ItemIndex = 0
            ; LoopCollectionNode37_ItemIndex < Group.Gunner.Guns.Count; LoopCollectionNode37_ItemIndex++
            ) {
                LoopCollectionNode37_Item = Group.Gunner.Guns[LoopCollectionNode37_ItemIndex];
                LoopCollectionNode37_Next();
            }
        }
        
        private void LoopCollectionNode38_Next() {
            // SetVariableNode
            LoopCollectionNode38_Item.State = (uFrameECSExample.GunState)EnumValueNode42;
        }
        
        private void ActionNode36_no() {
            // LoopCollectionNode
            for (var LoopCollectionNode38_ItemIndex = 0
            ; LoopCollectionNode38_ItemIndex < Group.Gunner.Guns.Count; LoopCollectionNode38_ItemIndex++
            ) {
                LoopCollectionNode38_Item = Group.Gunner.Guns[LoopCollectionNode38_ItemIndex];
                LoopCollectionNode38_Next();
            }
        }
    }
}
