// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class PointsOnDestroyComponentDestroyed {
        
        public PointsOnDestroy Group;
        
        private PointsOnDestroy _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private uFrameECSExample.WavesGame LoopGroupNode20_Item = default( uFrameECSExample.WavesGame );
        
        private int ActionNode21_a = default( System.Int32 );
        
        private int ActionNode21_b = default( System.Int32 );
        
        private int ActionNode21_Result = default( System.Int32 );
        
        public PointsOnDestroy Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // LoopGroupNode
            var LoopGroupNode20_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSExample.WavesGame>().Components;
            for (var LoopGroupNode20_ItemIndex = 0
            ; LoopGroupNode20_ItemIndex < LoopGroupNode20_GroupComponents.Count; LoopGroupNode20_ItemIndex++
            ) {
                LoopGroupNode20_Item = LoopGroupNode20_GroupComponents[LoopGroupNode20_ItemIndex];
                LoopGroupNode20_Next();
            }
        }
        
        private void LoopGroupNode20_Next() {
            ActionNode21_a = LoopGroupNode20_Item.Score;
            ActionNode21_b = Group.Points;
            // ActionNode
            // Visit uFrame.ECS.Actions.IntLibrary.Add
            ActionNode21_Result = uFrame.ECS.Actions.IntLibrary.Add(ActionNode21_a, ActionNode21_b);
            // SetVariableNode
            LoopGroupNode20_Item.Score = (System.Int32)ActionNode21_Result;
        }
    }
}
