// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class PlayerSystemGameOverHandler {
        
        public WavesGame Group;
        
        private uFrameECSExample.GameOver _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private uFrameECSExample.Player LoopGroupNode32_Item = default( uFrameECSExample.Player );
        
        private uFrame.ECS.UnityUtilities.SavePlayerData PublishEventNode34_Result = default( uFrame.ECS.UnityUtilities.SavePlayerData );
        
        public uFrameECSExample.GameOver Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // LoopGroupNode
            var LoopGroupNode32_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSExample.Player>().Components;
            for (var LoopGroupNode32_ItemIndex = 0
            ; LoopGroupNode32_ItemIndex < LoopGroupNode32_GroupComponents.Count; LoopGroupNode32_ItemIndex++
            ) {
                LoopGroupNode32_Item = LoopGroupNode32_GroupComponents[LoopGroupNode32_ItemIndex];
                LoopGroupNode32_Next();
            }
        }
        
        private void LoopGroupNode32_Next() {
            // SetVariableNode
            LoopGroupNode32_Item.BestScore = (System.Int32)Group.Score;
            // PublishEventNode
            var PublishEventNode34_Event = new SavePlayerData();
            System.Publish(PublishEventNode34_Event);
            PublishEventNode34_Result = PublishEventNode34_Event;
        }
    }
}
