// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class ProjectileCreated {
        
        public Projectile Group;
        
        private Projectile _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode9_go = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode9_component = default( UnityEngine.MonoBehaviour );
        
        private UnityEngine.Rigidbody ActionNode9_Result = default( UnityEngine.Rigidbody );
        
        private UnityEngine.Vector3 ActionNode10_a = default( UnityEngine.Vector3 );
        
        private float ActionNode10_b = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode10_Result = default( UnityEngine.Vector3 );
        
        public Projectile Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode9_go = Group.Entity.gameObject;
            // ActionNode
            // Visit uFrame.ECS.Actions.UnityLibrary.GetRigidbody
            ActionNode9_Result = uFrame.ECS.Actions.UnityLibrary.GetRigidbody(ActionNode9_go, ActionNode9_component);
            ActionNode10_a = Group.Direction;
            ActionNode10_b = Group.Speed;
            // ActionNode
            // Visit uFrame.ECS.Actions.Vector3Library.Multiply
            ActionNode10_Result = uFrame.ECS.Actions.Vector3Library.Multiply(ActionNode10_a, ActionNode10_b);
            // SetVariableNode
            ActionNode9_Result.velocity = (UnityEngine.Vector3)ActionNode10_Result;
        }
    }
}
