// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class ScrollSystemUpdateHandler {
        
        public BackgroundScroller Group;
        
        private uFrame.ECS.APIs.ISystemUpdate _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private UnityEngine.Vector3 ActionNode16_a = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 Vector3Node15 = new UnityEngine.Vector3(0f,0f,1f);
        
        private float ActionNode10_Result = default( System.Single );
        
        private float ActionNode18_a = default( System.Single );
        
        private float ActionNode18_b = default( System.Single );
        
        private float ActionNode18_Result = default( System.Single );
        
        private float ActionNode13_t = default( System.Single );
        
        private float ActionNode13_length = default( System.Single );
        
        private float ActionNode13_Result = default( System.Single );
        
        private float ActionNode16_b = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode16_Result = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode17_a = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode17_b = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode17_Result = default( UnityEngine.Vector3 );
        
        public uFrame.ECS.APIs.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode16_a = Vector3Node15;
            // ActionNode
            // Visit uFrame.ECS.Actions.TimeLibrary.GetTime
            ActionNode10_Result = uFrame.ECS.Actions.TimeLibrary.GetTime();
            ActionNode18_a = ActionNode10_Result;
            ActionNode18_b = Group.ScrollSpeed;
            // ActionNode
            // Visit uFrame.ECS.Actions.FloatLibrary.Multiply
            ActionNode18_Result = uFrame.ECS.Actions.FloatLibrary.Multiply(ActionNode18_a, ActionNode18_b);
            ActionNode13_t = ActionNode18_Result;
            ActionNode13_length = Group.TileSizeZ;
            // ActionNode
            // Visit UnityEngine.Mathf.Repeat
            ActionNode13_Result = UnityEngine.Mathf.Repeat(ActionNode13_t, ActionNode13_length);
            ActionNode16_b = ActionNode13_Result;
            // ActionNode
            // Visit uFrame.ECS.Actions.Vector3Library.Multiply
            ActionNode16_Result = uFrame.ECS.Actions.Vector3Library.Multiply(ActionNode16_a, ActionNode16_b);
            ActionNode17_a = ActionNode16_Result;
            ActionNode17_b = Group.StartPosition;
            // ActionNode
            // Visit uFrame.ECS.Actions.Vector3Library.Add
            ActionNode17_Result = uFrame.ECS.Actions.Vector3Library.Add(ActionNode17_a, ActionNode17_b);
            // SetVariableNode
            Group.Entity.transform.position = (UnityEngine.Vector3)ActionNode17_Result;
        }
    }
}
