// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class SetScoreLabel {
        
        public WavesGame Group;
        
        public int OldValue;
        
        public int NewValue;
        
        private WavesGame _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private uFrameECSExample.ScoreText LoopGroupNode43_Item = default( uFrameECSExample.ScoreText );
        
        private string FormatStringAction44_Result = default( System.String );
        
        public WavesGame Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // LoopGroupNode
            var LoopGroupNode43_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSExample.ScoreText>().Components;
            for (var LoopGroupNode43_ItemIndex = 0
            ; LoopGroupNode43_ItemIndex < LoopGroupNode43_GroupComponents.Count; LoopGroupNode43_ItemIndex++
            ) {
                LoopGroupNode43_Item = LoopGroupNode43_GroupComponents[LoopGroupNode43_ItemIndex];
                LoopGroupNode43_Next();
            }
        }
        
        private void LoopGroupNode43_Next() {
            // FormatStringAction
            FormatStringAction44_Result = string.Format(@"Score: {0}", Group.Score);
            // SetVariableNode
            LoopGroupNode43_Item.Text.text = (System.String)FormatStringAction44_Result;
        }
    }
}
