// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class ShooterFixedUpdateHandler {
        
        public Movable Group;
        
        private uFrame.ECS.APIs.ISystemFixedUpdate _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private string ActionNode43_axisName = default( System.String );
        
        private string StringNode44 = "Horizontal";
        
        private float ActionNode43_Result = default( System.Single );
        
        private string ActionNode46_axisName = default( System.String );
        
        private string StringNode47 = "Vertical";
        
        private float ActionNode46_Result = default( System.Single );
        
        private UnityEngine.GameObject ActionNode38_go = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode38_component = default( UnityEngine.MonoBehaviour );
        
        private UnityEngine.Rigidbody ActionNode38_Result = default( UnityEngine.Rigidbody );
        
        private UnityEngine.Rigidbody ActionNode17_rigidBody = default( UnityEngine.Rigidbody );
        
        private float ActionNode17_x = default( System.Single );
        
        private float ActionNode17_y = default( System.Single );
        
        private float ActionNode17_z = default( System.Single );
        
        private float ActionNode17_speed = default( System.Single );
        
        private UnityEngine.Rigidbody ActionNode49_rigidBody = default( UnityEngine.Rigidbody );
        
        private float ActionNode49_x = default( System.Single );
        
        private float ActionNode49_y = default( System.Single );
        
        private float ActionNode40_a = default( System.Single );
        
        private float ActionNode40_b = default( System.Single );
        
        private float ActionNode40_result = default( System.Single );
        
        private float ActionNode49_z = default( System.Single );
        
        public uFrame.ECS.APIs.ISystemFixedUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // ActionGroupNode
            ActionNode43_axisName = StringNode44;
            // ActionNode
            // Visit UnityEngine.Input.GetAxis
            ActionNode43_Result = UnityEngine.Input.GetAxis(ActionNode43_axisName);
            // SetVariableNode
            Group.Horizontal = (System.Single)ActionNode43_Result;
            ActionNode46_axisName = StringNode47;
            // ActionNode
            // Visit UnityEngine.Input.GetAxis
            ActionNode46_Result = UnityEngine.Input.GetAxis(ActionNode46_axisName);
            // SetVariableNode
            Group.Vertical = (System.Single)ActionNode46_Result;
            ActionNode38_go = Group.Entity.gameObject;
            // ActionNode
            // Visit uFrame.ECS.Actions.UnityLibrary.GetRigidbody
            ActionNode38_Result = uFrame.ECS.Actions.UnityLibrary.GetRigidbody(ActionNode38_go, ActionNode38_component);
            ActionNode17_rigidBody = ActionNode38_Result;
            ActionNode17_x = Group.Horizontal;
            ActionNode17_z = Group.Vertical;
            ActionNode17_speed = Group.Speed;
            // ActionNode
            // Visit uFrame.ECS.Actions.RigidbodyLibrary.SetVelocityWithSpeed
            uFrame.ECS.Actions.RigidbodyLibrary.SetVelocityWithSpeed(ActionNode17_rigidBody, ActionNode17_x, ActionNode17_y, ActionNode17_z, ActionNode17_speed);
            ActionNode49_rigidBody = ActionNode38_Result;
            ActionNode40_a = ActionNode38_Result.velocity.x;
            ActionNode40_b = Group.Tilt;
            // ActionNode
            // Visit uFrame.ECS.Actions.MathLibrary.Multiply
            uFrame.ECS.Actions.MathLibrary.Multiply(ActionNode40_a, ActionNode40_b, out ActionNode40_result);
            ActionNode49_z = ActionNode40_result;
            // ActionNode
            // Visit uFrame.ECS.Actions.RigidbodyLibrary.SetRigidbodyRotation
            uFrame.ECS.Actions.RigidbodyLibrary.SetRigidbodyRotation(ActionNode49_rigidBody, ActionNode49_x, ActionNode49_y, ActionNode49_z);
        }
    }
}
