// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class UISystemPointerClickDispatcherHandler {
        
        public PlayGameButton Source;
        
        private uFrame.ECS.UnityUtilities.PointerClickDispatcher _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private UnityEngine.GameObject LoopCollectionNode37_Item = default( UnityEngine.GameObject );
        
        private UnityEngine.GameObject ActionNode38_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.Vector3 ActionNode38_position = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode38_rotation = default( UnityEngine.Vector3 );
        
        private UnityEngine.GameObject ActionNode38_Result = default( UnityEngine.GameObject );
        
        public uFrame.ECS.UnityUtilities.PointerClickDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // LoopCollectionNode
            for (var LoopCollectionNode37_ItemIndex = 0
            ; LoopCollectionNode37_ItemIndex < Source.InstantiateItems.Count; LoopCollectionNode37_ItemIndex++
            ) {
                LoopCollectionNode37_Item = Source.InstantiateItems[LoopCollectionNode37_ItemIndex];
                LoopCollectionNode37_Next();
            }
        }
        
        private void LoopCollectionNode37_Next() {
            ActionNode38_gameObject = LoopCollectionNode37_Item;
            // ActionNode
            // Visit uFrame.ECS.Actions.GameObjects.Instantiate
            ActionNode38_Result = uFrame.ECS.Actions.GameObjects.Instantiate(ActionNode38_gameObject, ActionNode38_position, ActionNode38_rotation);
        }
    }
}
