// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class WavesGameSystemGameOverHandler {
        
        public WavesGame Group;
        
        private uFrameECSExample.GameOver _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode25_gameObject = default( UnityEngine.GameObject );
        
        private int ActionNode27_in = default( System.Int32 );
        
        private int IntNode26 = 1;
        
        private float ActionNode27_Result = default( System.Single );
        
        private float ActionNode25_time = default( System.Single );
        
        public uFrameECSExample.GameOver Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode25_gameObject = Group.Entity.gameObject;
            ActionNode27_in = IntNode26;
            // ActionNode
            // Visit uFrame.ECS.Actions.Converter.IntToFloat
            ActionNode27_Result = uFrame.ECS.Actions.Converter.IntToFloat(ActionNode27_in);
            ActionNode25_time = ActionNode27_Result;
            // ActionNode
            // Visit uFrame.ECS.Actions.DestroyLibrary.DestroyGameObject
            uFrame.ECS.Actions.DestroyLibrary.DestroyGameObject(ActionNode25_gameObject, ActionNode25_time);
        }
    }
}
