// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class WeaponSystemUpdateHandler {
        
        public ShootingGuns Group;
        
        private uFrame.ECS.APIs.ISystemUpdate _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private float ActionNode15_Result = default( System.Single );
        
        private float ActionNode14_a = default( System.Single );
        
        private float ActionNode14_b = default( System.Single );
        
        private bool ActionNode14_Result = default( System.Boolean );
        
        private float ActionNode43_a = default( System.Single );
        
        private float ActionNode43_b = default( System.Single );
        
        private float ActionNode43_Result = default( System.Single );
        
        private UnityEngine.GameObject ActionNode18_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.Vector3 ActionNode18_position = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode18_rotation = default( UnityEngine.Vector3 );
        
        private UnityEngine.GameObject ActionNode18_Result = default( UnityEngine.GameObject );
        
        private UnityEngine.GameObject ActionNode19_gameObject = default( UnityEngine.GameObject );
        
        private float ActionNode19_time = default( System.Single );
        
        private float FloatNode20 = 3F;
        
        public uFrame.ECS.APIs.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // ActionNode
            // Visit uFrame.ECS.Actions.TimeLibrary.GetTime
            ActionNode15_Result = uFrame.ECS.Actions.TimeLibrary.GetTime();
            ActionNode14_a = ActionNode15_Result;
            ActionNode14_b = Group.Gun.NextFire;
            // ActionNode
            // Visit uFrame.ECS.Actions.Comparisons.GreaterThan
            ActionNode14_Result = uFrame.ECS.Actions.Comparisons.GreaterThan(ActionNode14_a, ActionNode14_b, ActionNode14_yes, ActionNode14_no);
        }
        
        private void ActionNode14_yes() {
            ActionNode43_a = ActionNode15_Result;
            ActionNode43_b = Group.Gun.FireRate;
            // ActionNode
            // Visit uFrame.ECS.Actions.FloatLibrary.Add
            ActionNode43_Result = uFrame.ECS.Actions.FloatLibrary.Add(ActionNode43_a, ActionNode43_b);
            // SetVariableNode
            Group.Gun.NextFire = (System.Single)ActionNode43_Result;
            ActionNode18_gameObject = Group.Gun.ProjectilePrefab;
            ActionNode18_position = Group.Entity.transform.position;
            // ActionNode
            // Visit uFrame.ECS.Actions.GameObjects.Instantiate
            ActionNode18_Result = uFrame.ECS.Actions.GameObjects.Instantiate(ActionNode18_gameObject, ActionNode18_position, ActionNode18_rotation);
            ActionNode19_gameObject = ActionNode18_Result.gameObject;
            ActionNode19_time = FloatNode20;
            // ActionNode
            // Visit uFrame.ECS.Actions.DestroyLibrary.DestroyGameObject
            uFrame.ECS.Actions.DestroyLibrary.DestroyGameObject(ActionNode19_gameObject, ActionNode19_time);
        }
        
        private void ActionNode14_no() {
        }
    }
}
